PaPlWebsite/Controllers/ReportArrivalController.cs
using PaPlWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PaPlWebsite.Controllers
{
    public class ReportArrivalController : Controller
    {
        // GET: ReportArrival
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(ReportHop reportHop)
        {
            using (var client = new HttpClient())
            {
                string content = "";

                var response = await client.PostAsync("https://papl.azurewebsites.net/parcel/" + reportHop.ParcelId
                    + "/reportDelivery",
                    new StringContent(content, Encoding.UTF8, "application/json"));
                var jsonResult = await response.Content.ReadAsStringAsync();

                TempData["data"] = reportHop.ParcelId;
                return RedirectToAction("Index", "ReportResult");
            }

        }
    }
}

PaPlWebsite/Controllers/ReportHopController.cs
using PaPlWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PaPlWebsite.Controllers
{
    public class ReportHopController : Controller
    {
        // GET: ReportHop
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(ReportHop reportHop)
        {
            using (var client = new HttpClient())
            {
                string content = "";

                var response = await client.PostAsync("https://papl.azurewebsites.net/parcel/" + reportHop.ParcelId 
                    + "/reportHop/" + reportHop.HopCode,
                    new StringContent(content, Encoding.UTF8, "application/json"));
                var jsonResult = await response.Content.ReadAsStringAsync();

                TempData["data"] = reportHop.ParcelId;
                return RedirectToAction("Index", "ReportResult");
            }

        }
    }
}

PaPlWebsite/Controllers/TrackController.cs
using Newtonsoft.Json;
using PaPlWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace PaPlWebsite.Controllers
{
    public class TrackController : Controller
    {
        // GET: Track
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(TrackingId trackingId)
        {
            using (var client = new HttpClient())
            {
                //var content = new StringContent("");

                var response = await client.GetAsync("https://papl.azurewebsites.net/parcel/" + trackingId.Id);
                var jsonResult = await response.Content.ReadAsStringAsync();
                //var model = GetModel(jsonResult);
                //return jsonResult;

                TempData["data"] = jsonResult;
                return RedirectToAction("Index", "TrackResult");
            }

        }

        private TrackingInfo GetModel(string text)
        {
            return JsonConvert.DeserializeObject<TrackingInfo>(text);
        }


    }
}

PaPlWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meine ASP.NET-Anwendung</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <div class="navbar navbar-expand-lg navbar-light navbar-fixed-top" style="background-color: #dbecf8;">
        <div class="container">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PaPl Parcel Service", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Submit", "Index", "Submit")</li>
                    <li>@Html.ActionLink("Track Parcel", "Index", "Track")</li>
                    <li>@Html.ActionLink("Report Hop", "Index", "ReportHop")</li>
                    <li>@Html.ActionLink("Report Delivery", "Index", "ReportArrival")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meine ASP.NET-Anwendung</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>